title: "EDM Portfolio"
#description: "Enterprise Data Management Portfolio"
#author: Lozano, Andrei F.
#remote_theme: pages-themes/minimal@v0.2.0


#show_downloads: true

#github:
  #is_project_page: true

#plugins:
  #- jekyll-remote-theme

theme: jekyll-theme-minimal
